name: terraform

on:
  workflow_call:
    inputs:
      environment:
        required: false
        default: ''
        type: string

    secrets:
      aws-access-key-id:
        required: false
      aws-secret-access-key:
        required: false
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}

jobs:
  setup-test:
    runs-on: ubuntu-latest
    steps:
      - id: setVariables
        run: |
          echo "halo"


